name: validate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    uses: int128/renovate-config-validator-workflow/.github/workflows/validate.yaml@8d4b5d44faceb7fc470ebf85cfbc9a90efad2295 # main
    with:
      config: .github/renovate.* *.json
