name: validate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    uses: int128/renovate-config-validator-workflow/.github/workflows/validate.yaml@bf950d807d652d6aa2f049907a7a6d623978ca43 # main
    with:
      config: .github/renovate.* *.json
