name: validate

on:
  pull_request:
    paths:
      - .github/workflows/validate.yaml
      - .github/renovate.*
      - '*.json'
  push:
    branches:
      - main

jobs:
  validate:
    uses: int128/renovate-base/.github/workflows/validate.yaml@main
    with:
      config: .github/renovate.* *.json
