name: validate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    uses: int128/renovate-config-validator-workflow/.github/workflows/validate.yaml@daf257785163a4c8448da3820b1463e9b8d9c5d1 # main
    with:
      config: .github/renovate.* *.json
